import { HereBase, HereMarker } from './here.common';
export declare class Here extends HereBase {
    private _layoutId;
    private fragment;
    private listener;
    private context;
    private FRAGMENT_ID;
    private isReady;
    private dragListener;
    private gestureListener;
    private nativeMarkers;
    private markersCallback;
    private markers;
    private nativeCircles;
    private circles;
    private navigationManager;
    private navigationManagerListener;
    private positionListener;
    private navigationRoute;
    private navigationRouteBoundingBox;
    private navigationArrowIcon;
    private navigationArrow;
    private routeOptions;
    private mapRoute;
    private navigationFollow;
    constructor();
    static init(appId: string, appCode: string, licenseKey: string): void;
    createNativeView(): Object;
    initNativeView(): void;
    disposeNativeView(): void;
    toggleScroll(enable: boolean): void;
    toggleZoom(enable: boolean): void;
    _getMarkersCount(): number;
    _requestPremision(): any;
    toNextWaypoint(): void;
    toPrevWaypoint(): void;
    setCenter(lat: number, lon: number, animated: boolean): Promise<any>;
    showWay(): any;
    calculateRoute(points: any): Promise<any>;
    startNavigation(): Promise<any>;
    startSimulation(): Promise<any>;
    stopNavigation(): Promise<any>;
    addMarkers(markers: HereMarker[]): Promise<any>;
    removeMarkers(markers?: number[]): Promise<any>;
    updateMarkers(markers: HereMarker[]): Promise<any>;
    updateMarker(marker: HereMarker): Promise<any>;
}
